version: '3'

services:
  server:
    container_name: h2o_mruby_server
    ports:
      - 8080:8080
    image: yyagi/h2o-mruby-server
    depends_on:
      - redis

  redis:
    container_name: h2o_redis
    image: redis:4.0.10
    ports:
      - 16379:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis:
    driver: local
